name: Munki Auto-Promote

on:
  workflow_dispatch:
  schedule:
    - cron: 00 13 * * * # Every weekday at 1300 GMT
jobs:
  munki-autopromote:
    runs-on: macos-latest
    timeout-minutes: 15
    env:
      MUNKI_VERSION: 6.4.0
      MUNKI_EXPLICIT_VERSION: 6.4.0.4627
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.RW_REPO_TOKEN }}
        fetch-depth: 1

    - name: Install Munki
      uses: joncrain/macos-pkg-install@7134d2a14cf37a88794d794ea0281e1e84161a51 #v1
      with:
        pkg_url: https://github.com/munki/munki/releases/download/v${{ env.MUNKI_VERSION }}/munkitools-${{ env.MUNKI_EXPLICIT_VERSION }}.pkg

    - name: Run makecatalogs
      run: /usr/local/munki/makecatalogs "$GITHUB_WORKSPACE" -s
    
    - name: Setup Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d #v5.1.0
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r autopromote/requirements.txt
        pip3 install pyyaml

    - name: Run Autopromote
      run: |
        python autopromote/autopromote.py
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

    - name: Run makecatalogs
      run: /usr/local/munki/makecatalogs "$GITHUB_WORKSPACE" -s

    - name: Create Branch and Commit Changes
      uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842
      with:
        file_pattern: 'pkgsinfo/* autopromote/results.plist'
        create_branch: true
        branch: autopromote_pkgsinfo-files-updates
        commit_message: Pkgsinfo files updated with new promotion schedule.
